<?php
declare(strict_types=1);
/**
 * Plugin Name:       Aldus — Block Compositor
 * Plugin URI:        https://github.com/RegionallyFamous/aldus
 * Description:       You write it. Aldus designs it. Sixteen layout styles for your content — pick the one that fits, and it becomes real WordPress blocks.
 * Version:           1.2.0
 * Requires at least: 6.4
 * Requires PHP:      8.0
 * Author:            Regionally Famous
 * Author URI:        https://regionallyfamous.com
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       aldus
 * Domain Path:       /languages
 * Update URI:        https://github.com/RegionallyFamous/aldus
 * Requires Plugins:
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'ALDUS_VERSION', '1.2.0' );
define( 'ALDUS_PATH', plugin_dir_path( __FILE__ ) );
define( 'ALDUS_URL', plugin_dir_url( __FILE__ ) );

register_activation_hook( __FILE__, 'aldus_activate' );
register_deactivation_hook( __FILE__, 'aldus_deactivate' );

/**
 * Runs on plugin activation.
 *
 * Stores the installed version so future activations can detect upgrades and
 * run any needed migration logic. No rewrite rules are registered at this time,
 * so no flush is required.
 */
function aldus_activate(): void {
	if ( ! get_option( 'aldus_version' ) ) {
		add_option( 'aldus_version', ALDUS_VERSION, '', false );
	}
}

/**
 * Runs on plugin deactivation.
 */
function aldus_deactivate(): void {}

add_action( 'plugins_loaded', 'aldus_init' );

/**
 * Bootstraps all plugin functionality.
 */
function aldus_init(): void {
	require_once ALDUS_PATH . 'includes/api.php';
	require_once ALDUS_PATH . 'includes/bindings.php';
	require_once ALDUS_PATH . 'includes/block-html.php';
	require_once ALDUS_PATH . 'includes/templates.php';
	require_once ALDUS_PATH . 'includes/patterns.php';

	add_action( 'init', 'aldus_register_block' );
	add_action( 'init', fn() => load_plugin_textdomain( 'aldus', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' ) );
	add_action( 'rest_api_init', 'aldus_register_rest_routes' );

	// Flush cached theme data whenever the active theme or Customizer settings change.
	add_action( 'switch_theme',         'aldus_flush_theme_cache' );
	add_action( 'customize_save_after', 'aldus_flush_theme_cache' );

	// Inject Aldus spacing presets and CSS custom properties into the active theme's
	// theme.json data so generated layouts render consistently regardless of theme.
	add_filter( 'wp_theme_json_data_theme', 'aldus_inject_theme_json' );

	// Register the Aldus block pattern category for future pattern library integration.
	register_block_pattern_category(
		'aldus',
		[
			'label'       => __( 'Aldus', 'aldus' ),
			'description' => __( 'Layouts generated by the Aldus AI Block Compositor.', 'aldus' ),
		]
	);

	// Register a custom block inserter category so Aldus appears in its own section.
	add_filter( 'block_categories_all', 'aldus_register_block_category' );

	// Add a "How to use" link to the plugin row on the Plugins admin page.
	add_filter( 'plugin_action_links_' . plugin_basename( __FILE__ ), 'aldus_plugin_action_links' );

	// Restrict the Block Hook declared in block.json to FSE templates only.
	add_filter( 'hooked_block_types', 'aldus_hooked_block_types', 10, 4 );

	// Warn about deprecated filter usage.
	aldus_check_deprecated_filters();
}

/**
 * Prepends the Aldus category to the block inserter category list.
 *
 * @param array<int, array<string, string>> $categories Existing block categories.
 * @return array<int, array<string, string>>
 */
function aldus_register_block_category( array $categories ): array {
	return array_merge(
		[
			[
				'slug'  => 'aldus',
				'title' => __( 'Aldus', 'aldus' ),
				'icon'  => 'table-col-after',
			],
		],
		$categories
	);
}

/**
 * Adds action links to the plugin row on the Plugins admin page.
 *
 * @param array<string, string> $links Existing action links.
 * @return array<string, string>
 */
function aldus_plugin_action_links( array $links ): array {
	$how_to_use = sprintf(
		'<a href="%s" target="_blank" rel="noopener noreferrer">%s</a>',
		'https://github.com/RegionallyFamous/aldus/wiki',
		__( 'How to use', 'aldus' )
	);
	return array_merge( [ 'how_to_use' => $how_to_use ], $links );
}

/**
 * Restricts the Block Hook to FSE block templates only.
 *
 * The hook declared in block.json makes sense inside the Site Editor, where
 * Aldus can seed an empty layout in a blank template. It should not fire when
 * WordPress is rendering individual post or page content on the front end —
 * that would silently inject the compositor into every published page.
 *
 * WordPress passes a WP_Block_Template for FSE templates, a WP_Post for
 * classic template parts / patterns, and null in some edge cases.
 * Checking instanceof WP_Block_Template is the narrowest safe guard here.
 *
 * @param string[]                              $hooked_blocks  Block types to insert at this position.
 * @param string                                $position       Relative position (e.g. 'firstChild').
 * @param string                                $anchor         Anchor block type.
 * @param WP_Block_Template|WP_Post|array|null  $context        Template, post, reusable-block array, or null.
 * @return string[]
 */
function aldus_hooked_block_types( array $hooked_blocks, string $position, string $anchor, $context ): array {
	if ( ! ( $context instanceof WP_Block_Template ) ) {
		return array_diff( $hooked_blocks, [ 'aldus/layout-generator' ] );
	}
	return $hooked_blocks;
}

/**
 * Issues _doing_it_wrong() notices if third-party code has attached callbacks
 * to Aldus filter hooks that may be renamed or removed in a future release.
 *
 * This is a no-op for all current hooks (none have been deprecated yet) but
 * establishes the pattern so that future renames can warn developers cleanly.
 */
function aldus_check_deprecated_filters(): void {
	/**
	 * Map of deprecated hook name => message describing the replacement.
	 * Populate this array when a hook is renamed or removed.
	 *
	 * Example:
	 * 'aldus_old_hook' => 'Use aldus_new_hook instead. See https://github.com/RegionallyFamous/aldus/wiki for migration notes.',
	 *
	 * @var array<string, string>
	 */
	$deprecated = [];

	foreach ( $deprecated as $hook => $message ) {
		if ( has_filter( $hook ) ) {
			_doing_it_wrong(
				$hook,
				esc_html( $message ),
				'1.0.0'
			);
		}
	}
}

/**
 * Flush all Aldus object-cache entries for theme data.
 *
 * Hooked to switch_theme and customize_save_after so the color palette,
 * font sizes, and gradient entries are re-read after any theme change.
 */
function aldus_flush_theme_cache(): void {
	wp_cache_delete( 'aldus_palette_'    . ALDUS_VERSION, 'aldus' );
	wp_cache_delete( 'aldus_font_sizes_' . ALDUS_VERSION, 'aldus' );
	wp_cache_delete( 'aldus_gradients_'  . ALDUS_VERSION, 'aldus' );
}

/**
 * Registers the Gutenberg block from the compiled build directory.
 *
 * Uses wp_register_block_metadata_collection() (WP 6.7+) when available for
 * improved performance — it pre-processes the block metadata manifest so
 * WordPress can resolve block.json without repeated filesystem lookups.
 */
function aldus_register_block(): void {
	$build_path = ALDUS_PATH . 'build';
	if ( ! is_dir( $build_path ) || ! file_exists( $build_path . '/block.json' ) ) {
		return;
	}

	if ( function_exists( 'wp_register_block_metadata_collection' ) ) {
		wp_register_block_metadata_collection( $build_path, [ $build_path . '/block.json' ] );
	}

	register_block_type( $build_path );

	// Load a minimal frontend stylesheet only on pages that contain this block.
	// Passing 'path' lets WordPress inline the stylesheet above the fold rather
	// than emitting a <link> tag, which avoids a render-blocking request for
	// the small number of pages where this fires.
	wp_enqueue_block_style(
		'aldus/layout-generator',
		[
			'handle' => 'aldus-frontend',
			'src'    => ALDUS_URL . 'build/frontend.css',
			'ver'    => ALDUS_VERSION,
			'path'   => ALDUS_PATH . 'build/frontend.css',
		]
	);

	// Defer the editor script — it is large and has no dependency that requires
	// synchronous execution.  The 'strategy' data key is respected by WP 6.3+.
	wp_script_add_data( 'aldus-aldus-layout-generator-editor-script', 'strategy', 'defer' );

	// Emit a modulepreload hint for the WebLLM runtime chunk so it starts
	// downloading as soon as the block editor is opened, before the user clicks
	// "Make it happen".
	add_action( 'admin_head', 'aldus_webllm_modulepreload' );

	// Register the WebLLM runtime as a native Script Module (WP 6.5+).
	// The edit.js dynamic import() checks for window.__aldusScriptModules and
	// uses the module URL from there when available, falling back to the webpack
	// chunk for older WordPress versions.
	if ( function_exists( 'wp_register_script_module' ) ) {
		wp_register_script_module(
			'@aldus/webllm-runtime',
			ALDUS_URL . 'build/692.js',
			[],
			ALDUS_VERSION
		);
		// Surface the module URL to the editor script via an inline script.
		wp_add_inline_script(
			'aldus-aldus-layout-generator-editor-script',
			'window.__aldusScriptModules = window.__aldusScriptModules || {}; window.__aldusScriptModules["@aldus/webllm-runtime"] = ' . wp_json_encode( ALDUS_URL . 'build/692.js' ) . ';',
			'before'
		);
	}
}

/**
 * Injects site identity (name, description) for the editor LLM prompt.
 *
 * Hooked onto enqueue_block_editor_assets so the variable is available
 * as soon as the editor script loads — before the user interacts.
 */
function aldus_inline_site_data(): void {
	wp_add_inline_script(
		'aldus-aldus-layout-generator-editor-script',
		'window.__aldusSite = ' . wp_json_encode( [
			'name'        => get_bloginfo( 'name' ),
			'description' => get_bloginfo( 'description' ),
		] ) . ';',
		'before'
	);
}
add_action( 'enqueue_block_editor_assets', 'aldus_inline_site_data' );

/**
 * Prints a <link rel="modulepreload"> for the WebLLM runtime chunk on
 * block-editor screens only.
 *
 * This primes the browser cache so the chunk (≈5.9 MB) is available
 * immediately when the dynamic import() fires instead of loading on demand.
 */
function aldus_webllm_modulepreload(): void {
	$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
	if ( ! $screen || ! $screen->is_block_editor() ) {
		return;
	}
	$chunk_url = ALDUS_URL . 'build/692.js';
	printf(
		'<link rel="modulepreload" href="%s">' . "\n",
		esc_url( $chunk_url )
	);
}

/**
 * Merges Aldus-specific design tokens into the active theme's theme.json data.
 *
 * Injects custom spacing presets and CSS custom properties that generated
 * layouts depend on so they render consistently regardless of the active theme.
 * Uses the wp_theme_json_data_theme filter (WP 6.6+).
 *
 * @param WP_Theme_JSON_Data $theme_json Mutable theme.json data object.
 * @return WP_Theme_JSON_Data
 */
function aldus_inject_theme_json( WP_Theme_JSON_Data $theme_json ): WP_Theme_JSON_Data {
	$additions = [
		'version'  => 3,
		'settings' => [
			'spacing' => [
				'spacingSizes' => [
					[ 'slug' => 'aldus-section', 'size' => '80px',  'name' => 'Aldus Section' ],
					[ 'slug' => 'aldus-gap',     'size' => '40px',  'name' => 'Aldus Gap' ],
					[ 'slug' => 'aldus-tight',   'size' => '20px',  'name' => 'Aldus Tight' ],
				],
			],
		],
		'styles' => [
			'css' => '
				:root {
					--aldus-section-spacing: 80px;
					--aldus-gap: 40px;
					--aldus-tight: 20px;
					--aldus-overlay-dark: rgba(0,0,0,0.55);
					--aldus-overlay-accent: rgba(0,0,0,0.35);
				}
			',
		],
	];

	$theme_json->update_with( $additions );
	return $theme_json;
}
