<?php
/**
 * Plugin Name:       Aldus — Block Compositor
 * Plugin URI:        https://github.com/nicholasgasior/aldus
 * Description:       Drop in your content — headlines, paragraphs, a quote, an image — and Aldus figures out sixteen beautiful ways to lay it out. Pick the one you love and it becomes real WordPress blocks, ready to edit.
 * Version:           1.0.0
 * Requires at least: 6.4
 * Requires PHP:      8.0
 * Author:            Regionally Famous
 * Author URI:        https://regionallyfamous.com
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain:       aldus
 * Domain Path:       /languages
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'ALDUS_VERSION', '1.0.0' );
define( 'ALDUS_PATH', plugin_dir_path( __FILE__ ) );
define( 'ALDUS_URL', plugin_dir_url( __FILE__ ) );

register_activation_hook( __FILE__, 'aldus_activate' );
register_deactivation_hook( __FILE__, 'aldus_deactivate' );

/**
 * Runs on plugin activation.
 * No rewrite rules are registered, so no flush needed.
 */
function aldus_activate(): void {}

/**
 * Runs on plugin deactivation.
 */
function aldus_deactivate(): void {}

add_action( 'plugins_loaded', 'aldus_init' );

/**
 * Bootstraps all plugin functionality.
 */
function aldus_init(): void {
	require_once ALDUS_PATH . 'includes/api.php';
	require_once ALDUS_PATH . 'includes/templates.php';

	add_action( 'init', 'aldus_register_block' );
	add_action( 'init', fn() => load_plugin_textdomain( 'aldus', false, dirname( plugin_basename( __FILE__ ) ) . '/languages' ) );
	add_action( 'rest_api_init', 'aldus_register_rest_routes' );

	// Flush cached theme data whenever the active theme or Customizer settings change.
	add_action( 'switch_theme',         'aldus_flush_theme_cache' );
	add_action( 'customize_save_after', 'aldus_flush_theme_cache' );

	// Register the Aldus block pattern category for future pattern library integration.
	register_block_pattern_category(
		'aldus',
		[
			'label'       => __( 'Aldus', 'aldus' ),
			'description' => __( 'Layouts generated by the Aldus AI Block Compositor.', 'aldus' ),
		]
	);
}

/**
 * Flush all Aldus object-cache entries for theme data.
 *
 * Hooked to switch_theme and customize_save_after so the color palette,
 * font sizes, and gradient entries are re-read after any theme change.
 */
function aldus_flush_theme_cache(): void {
	wp_cache_delete( 'aldus_palette_'    . ALDUS_VERSION, 'aldus' );
	wp_cache_delete( 'aldus_font_sizes_' . ALDUS_VERSION, 'aldus' );
	wp_cache_delete( 'aldus_gradients_'  . ALDUS_VERSION, 'aldus' );
}

/**
 * Registers the Gutenberg block from the compiled build directory.
 */
function aldus_register_block(): void {
	$build_path = ALDUS_PATH . 'build';
	if ( is_dir( $build_path ) && file_exists( $build_path . '/block.json' ) ) {
		register_block_type( $build_path );
	}
}
