<?php
declare(strict_types=1);
/**
 * Block registration — registers the Aldus block type, frontend style, and WebLLM assets.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

// ---------------------------------------------------------------------------
// Block registration
// ---------------------------------------------------------------------------

/**
 * Registers the Aldus block type, frontend style, and WebLLM assets.
 *
 * Reads block metadata from build/block.json (generated by @wordpress/scripts).
 * Also hooks aldus_webllm_modulepreload onto admin_head so the model chunk
 * starts downloading as soon as the editor opens.
 */
function aldus_register_block(): void {
	$build_path = ALDUS_PATH . 'build';
	if ( ! is_dir( $build_path ) || ! file_exists( $build_path . '/block.json' ) ) {
		return;
	}
	// Guard against double-registration (e.g. when called from tests or during
	// theme switches).  WP_Block_Type_Registry::register() logs a notice when a
	// block type is registered a second time, which would surface as a test
	// failure in WP_UnitTestCase.
	if ( WP_Block_Type_Registry::get_instance()->is_registered( 'aldus/layout-generator' ) ) {
		return;
	}

	// Block registration — tiered by WP version for maximum efficiency.
	//   WP 6.8+: one call registers all blocks from the manifest, no separate
	//            register_block_type() needed (eliminates per-block filesystem reads).
	//   WP 6.7:  register metadata collection first, then register_block_type() still required.
	//   WP ≤ 6.6 or no manifest: plain register_block_type().
	//
	// IMPORTANT: wp_register_block_types_from_metadata_collection() receives
	// ALDUS_PATH (the plugin root) as the base path, NOT $build_path. The
	// manifest key 'build' means WordPress resolves files relative to
	// ALDUS_PATH/build/ — passing $build_path would make it look inside the
	// non-existent build/build/ directory, causing silent registration failure.
	$manifest = $build_path . '/blocks-manifest.php';
	if ( function_exists( 'wp_register_block_types_from_metadata_collection' ) && file_exists( $manifest ) ) {
		wp_register_block_types_from_metadata_collection( ALDUS_PATH, $manifest );
	} elseif ( function_exists( 'wp_register_block_metadata_collection' ) && file_exists( $manifest ) ) {
		wp_register_block_metadata_collection( $build_path, $manifest );
		register_block_type( $build_path );
	} else {
		register_block_type( $build_path );
	}

	// Load a minimal frontend stylesheet only on pages that contain this block.
	// Passing 'path' lets WordPress inline the stylesheet above the fold rather
	// than emitting a <link> tag, which avoids a render-blocking request for
	// the small number of pages where this fires.
	wp_enqueue_block_style(
		'aldus/layout-generator',
		array(
			'handle' => 'aldus-frontend',
			'src'    => ALDUS_URL . 'build/frontend.css',
			'ver'    => ALDUS_VERSION,
			'path'   => ALDUS_PATH . 'build/frontend.css',
		)
	);

	// Defer the editor script — it is large and has no dependency that requires
	// synchronous execution.  The 'strategy' data key is respected by WP 6.3+.
	wp_script_add_data( 'aldus-aldus-layout-generator-editor-script', 'strategy', 'defer' );

	// Emit a modulepreload hint for the WebLLM runtime chunk so it starts
	// downloading as soon as the block editor is opened, before the user clicks
	// "Make it happen".
	add_action( 'admin_head', 'aldus_webllm_modulepreload' );

	// Register the WebLLM runtime as a native Script Module (WP 6.5+).
	// The edit.js dynamic import() checks for window.__aldusScriptModules and
	// uses the module URL from there when available, falling back to the webpack
	// chunk for older WordPress versions.
	if ( function_exists( 'wp_register_script_module' ) ) {
		wp_register_script_module(
			'@aldus/webllm-runtime',
			ALDUS_URL . 'build/692.js',
			array(),
			ALDUS_VERSION
		);

		// Register the front-end Interactivity API store (WP 6.5+).
		// block.json declares this via viewScriptModule so WordPress loads it
		// automatically on pages that contain an Aldus-generated block.
		if ( file_exists( ALDUS_PATH . 'build/frontend-interactivity.js' ) ) {
			wp_register_script_module(
				'@aldus/interactivity',
				ALDUS_URL . 'build/frontend-interactivity.js',
				array( '@wordpress/interactivity' ),
				ALDUS_VERSION
			);
		}
		// Surface the module URL to the editor script via an inline script.
		wp_add_inline_script(
			'aldus-aldus-layout-generator-editor-script',
			'window.__aldusScriptModules = window.__aldusScriptModules || {};' .
			' window.__aldusScriptModules["@aldus/webllm-runtime"] = ' .
			wp_json_encode( ALDUS_URL . 'build/692.js' ) . ';',
			'before'
		);
	}

	// Load block CSS only when the block is present on the page rather than
	// unconditionally on every front-end request (WP 6.8+).
	add_filter( 'should_load_block_assets_on_demand', '__return_true' );
}

// ---------------------------------------------------------------------------
// Block editor capability settings
// ---------------------------------------------------------------------------

add_filter(
	'block_editor_settings_all',
	static function ( array $settings ): array {
		// Only editors and above can lock or unlock Aldus-generated layouts.
		// Contributors and authors see content-only editing and cannot add
		// new block-locking rules of their own.
		$settings['canLockBlocks'] = current_user_can( 'edit_others_posts' );
		return $settings;
	}
);

// ---------------------------------------------------------------------------
// WebLLM module preload
// ---------------------------------------------------------------------------

/**
 * Emits <link rel="modulepreload"> and <link rel="prefetch"> hints for the
 * WebLLM runtime chunk so the browser starts fetching the model as soon as
 * the block editor opens — before the user clicks "Make it happen".
 *
 * Hooked onto admin_head by aldus_register_block().
 */
function aldus_webllm_modulepreload(): void {
	$screen = function_exists( 'get_current_screen' ) ? get_current_screen() : null;
	if ( ! $screen || ! $screen->is_block_editor() ) {
		return;
	}
	$chunk_url = ALDUS_URL . 'build/692.js';
	// modulepreload for modern browsers; prefetch as fallback for older ones.
	printf(
		'<link rel="modulepreload" href="%1$s">' . "\n" .
		'<link rel="prefetch" as="script" href="%1$s">' . "\n",
		esc_url( $chunk_url )
	);
}
